bookers2-debug/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   devise_scope :user do
  	get 'user/sign_up' => 'devise/registrations#new'
  end
  root 'home#top'
  get '/home/about' => "home#about"
  get "search" => "searchs#search"

  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

bookers2-debug/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	# attachment :image
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
	  favorites.where(user_id: user.id).exists?
	end

    def self.search(search, word)
        if search == "1"
                        @book = Book.where(["title LIKE?","#{word}%"])
        elsif search == "2"
                        @book = Book.where(["title LIKE?","%#{word}"])
        elsif search == "3"
                        @book = Book.where(["title LIKE?","#{word}"])
        elsif search == "4"
                        @book = Book.where(["title LIKE?","%#{word}%"])
        else
                        @book = Book.all
        end
    end


end

bookers2-debug/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index, :show,:edit]
  before_action :correct_user,   only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @post = Book.new
    @book_comment = BookComment.new
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render :index
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render :edit
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destoy
  	redirect_to books_path, notice: "successfully delete book!"
  end



  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
  def correct_user
      @book = Book.find(params[:id])
      redirect_to(books_path) unless @book.user == current_user
  end
end

bookers2-debug/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-debug/app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Create Book",class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

bookers2-debug/app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>
<% if @book.errors.any? %>
<h4><%= @book.errors.count %>errors prohibited this book from being saved:</h4>
<ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
</ul>
<% end %>

<%= form_for(@book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit "Update Book",class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

bookers2-debug/app/views/books/index.html.erb
<div class="container">
<div class="row">
	<% if @book.errors.any? %>
 		<h4><br><%= @book.errors.count %>errors prohibited this book from being saved:</h4>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
	<div class="col-xs-3" style="background-color: white">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th></th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><% if book.favorited_by?(current_user) %>
                         <%= link_to book_favorites_path(book), method: :delete do %>
                         <span class="glyphicon glyphicon-heart" aria-hidden="true" ><%= book.favorites.count %></span>
                         <% end %>
                         <% else %>
                         <%= link_to book_favorites_path(book), method: :post do %>
                         <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"><%= book.favorites.count %></span>
                         <% end %>
                         <% end %></td>
					<td>コメント数:<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>
</div>

bookers2-debug/app/views/books/show.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @post %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>
					<td><% if @book.favorited_by?(current_user) %>
                         <%= link_to book_favorites_path(@book), method: :delete do %>
                         <span class="glyphicon glyphicon-heart" aria-hidden="true" ><%= @book.favorites.count %></span>
                         <% end %>
                         <% else %>
                         <%= link_to book_favorites_path(@book), method: :post do %>
                         <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"><%= @book.favorites.count %></span>
                         <% end %>
                         <% end %>
                         </td>
					<td>コメント数:<%= @book.book_comments.count %></td>
					<% if current_user.id == @book.user_id %>
					<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
				<% @book.book_comments.each do |book_comment| %>
				<p><%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<%= book_comment.comment %>
					<% if book_comment.user == current_user%>
                          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %>
                    <% end %></p>
				<% end %>
			<%= form_for [@book, @book_comment] do |f| %>
            <%= f.text_area :comment, rows:'5', class: "form-control" %>

             <%= f.submit "送信" %>
             <% end %>

	</div>
</div>
</div>