bookers2-debug/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   devise_scope :user do
  	get 'user/sign_up' => 'devise/registrations#new'
  end
  root 'home#top'
  get '/home/about' => "home#about"
  get "search" => "searchs#search"

  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]

end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy: false
  validates :name, presence: true, uniqueness: true,
                  length: {minimum: 2, maximum: 20}
  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :introduction, length: {maximum: 50}
  def self.search(search, word)
            if search == "1"
                    @user = User.where(['name LIKE ?', "#{word}%"])
            elsif search == "2"
                    @user = User.where(['name LIKE ?', "%#{word}"])
            elsif search == "3"
                    @user = User.where(['name LIKE ?', "#{word}"])
            elsif search == "4"
                    @user = User.where(['name LIKE ?', "%#{word}%"])
            else
                    @user = User.all
            end
    end


  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

bookers2-debug/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :index, :show,:edit]
  before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end
  def edit
  	@user = User.find(params[:id])
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: 'successfully updated user!'
  	else
      @users = User.all
  		render :edit
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
   unless params[:id].to_i == current_user.id
      redirect_to user_path(current_user)
    end
   end

end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     user == current_user
    end
end

bookers2-debug/app/views/users/_follow_form.html.erb
 <% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを外す", class: "btn btn-large follow-btn" %>
  <% end %>
  <% else %>
     <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large btn-primary follow-btn" %>
<% end %>
  <% end %>
  </div>
<% end %>

bookers2-debug/app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<%= render 'users/stats', user: user %>
</table>
<%= render 'users/follow_form', user: user %>
<% if current_user.id == @book.user_id %>
<div>
	<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

bookers2-debug/app/views/users/_stats.html.erb
 <% user ||= current_user %>
<div class="stats">
  <tr>
    <th>follows</th>
  <th><a href="<%= following_user_path(user) %>">
    <strong id="following" class="stat">
      <%= user.followings.count %>
    </strong>
  </a></th>
  </tr>
  <tr>
  <th>followers</th>
  <th><a href="<%= followers_user_path(user) %>">
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
  </a></th>
  </tr>
</div>

bookers2-debug/app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit 'Update User' %>
</div>

<% end %>

bookers2-debug/app/views/users/index.html.erb
<div class="container">
 <div class="row">
 	<div class="col-xs-3" style="background-color: white">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class=" col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th></th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= link_to (user) do %>
				<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
				</td>
			<td><%= user.name%></td>
			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<td><% unless current_user?(user) %>
             <% if current_user.following?(user) %>
             <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー外す",class: 'btn btn-link' %>
             <% end %>
             <% else %>
             <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
             <div><%= f.hidden_field :following_id %></div>
             <%= f.submit "フォローする",class: 'btn btn-link' %>
              <% end %>
             <% end %>
             <% end %></td>
			<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->
</div>
</div>
</div>

bookers2-debug/app/views/users/search.html.erb

<% if @user_or_book == "1"%>
    <h1>User</h1>
    <table>
        <% @users.each do |user| %>
        <thead>
            <tr>
                <th></th>
                <th><%= user.name %> </th>
            </tr>
        </thead>
        <% end %>
    </table>

<% elsif @user_or_book == "2" %>
    <h2>Post</h2>
    <table>
    <% @books.each do |post| %>
        <thead>
            <tr>
                <th></th>
                <th><%= book.title %></th>
            </tr>
        </thead>
    <% end %>
    </table>
<% else %>
<% end %>

bookers2-debug/app/views/users/show.html.erb
<div class="container">
 <div class="row">
 	<div class="col-xs-3" style="background-color: white">

<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>
</div>
<div class=" col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th></th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @user.books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
			<td>コメント数:<%= book.book_comments.count %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->
</div>
</div>
</div>

bookers2-debug/app/views/users/show_follow.html.erb

<section class="container">
<div class="row">
	<h1>Follow User</h1>
	<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
<% @user.followings.each do |user| %>
<tr>
  <td><%= link_to (user) do %>
				<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
				</td>
			<td><%= user.name%></td>
			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<td><% unless current_user?(user) %>
             <% if current_user.following?(user) %>
             <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー外す",class: 'btn btn-link' %>
             <% end %>
             <% else %>
             <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
             <div><%= f.hidden_field :following_id %></div>
             <%= f.submit "フォローする",class: 'btn btn-link' %>
              <% end %>
             <% end %>
             <% end %></td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>


<% end %>
</table>
</div>
</section>

bookers2-debug/app/views/users/show_follower.html.erb
<section class="container">
<div class="row">
	<h1>Follower User</h1>
	<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
			<th></th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
<% @user.followers.each do |user| %>
<tr>
  <td><%= link_to (user) do %>
				<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
				</td>
			<td><%= user.name%></td>
			<td>フォロー数:<%= user.followings.count %></td>
			<td>フォロワー数:<%= user.followers.count %></td>
			<td><% unless current_user?(user) %>
             <% if current_user.following?(user) %>
             <%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
              <%= f.submit "フォロー外す",class: 'btn btn-link' %>
             <% end %>
             <% else %>
             <%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
             <div><%= f.hidden_field :following_id %></div>
             <%= f.submit "フォローする",class: 'btn btn-link' %>
              <% end %>
             <% end %>
             <% end %></td>
  <td><%= link_to 'Show', user_path(user) %></td>
</tr>
</table>
<% end %>
</div>
</section>